openapi: 3.0.1

info:
  title: bakitup-service-2
  description: The Backitup Service
  version: 1.0.0

servers:
  - url: /api/v1

tags:
  - name: Backup
    description: Simple backup endpoints
  - name: Specification
    description: The swagger API specification

paths:
  /backup:
    get:
      tags:
        - Backup
      description: Fetch the entire backup configuration
      responses:
        200:
          description: Return the config entry with the specified ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        4XX:
          description: Config  not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Config not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Backup
      description: Add a new config entry
      requestBody:
        description: a config
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigEntry'
        required: true
      responses:
        201:
          description: Return the config with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        4XX:
          description: Config not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Config not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /backup/{id}:
    get:
      description: Get a given backup config entry by hash id
      tags:
        - Backup
      parameters:
        - name: id
          in: path
          description: The id of the config entry to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the config entry with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        4XX:
          description: Config entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Config entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /backup/{id}/#{command}:
    put:
      description: Perform an action with respect to a given backup id
      tags:
        - Backup
      parameters:
        - name: id
          in: path
          description: The id of the config entry to retrieve
          required: true
          schema:
            type: string
        - name: command
          in: path
          description: The command to run against the backup
          required: true
          schema:
            type: string
            enum: [start, stop]
      responses:
        200:
          description: the command was successfully ran against the backup entry with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        4XX:
          description: Config entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Config entry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

components:
  schemas:
    Config:
      type: array
      items:
        $ref: '#/components/schemas/ConfigObject' 
    Error:
      type: object
      additionalProperties: true

    ConfigObject:
      title: Config entry and its hash
      required:
        - hash
        - entry
      type: object
      properties:
        hash:
          type: string
          example: kisudifsl7866sd65s6
        entry:
          $ref: '#/components/schemas/ConfigEntry' 

    ConfigEntry:
      title: Single backup configuration entry
      required:
        - source
        - destination
      type: object
      properties:
        source:
          $ref: '#/components/schemas/Location' 
        destination:
          $ref: '#/components/schemas/Location' 

    Location:
      title: Location Entity
      type: object
      required:
        - path
      properties:
        path:
          type: string
          example: '\some\directory\path'
        volume:
          type: string
          example: 'Some-Volume-Name'
    
    Message:
      title: An arbitrary message 
      type: object
      required:
        - message
      properties:
        message:
          type: string
          nullable: true
          example: 'this is some arbitrary message'
